language: python

matrix:
  include:
    - os: linux
      python: 3.6
      dist: xenial
    - os: linux
      python: 3.7
      dist: xenial
    - os: linux
      python: 3.5

install:
- pip install -r requirements.txt
script:
- python -m unittest discover tests
- coverage run -p -m unittest discover tests
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - develop
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  user: keotl
  password:
    secure: "h82oYYrD5JexVoOKEAkapPMcl2EC3WmCqJG71Jc4Esg6ySj5BTQlUGGV1xcq8cWwamGwWcPxbA/sPbrZabr7k1EFmMLC40Cmkw8jBgftLJt/6cmmxgP5eS8W2YFbfM1gkz91fM4C/kUTVqGAU5XxRJ+2fW86N2/wnly8OsNLJbDSVwYxYuYF5YukW2P1bF0lsEtE7a/8qucuUebgjMJ1uK/Lvgh41lighbh+f0zCAV3uJWJjd3+inxMCmL7b6MqkaFShgCVwDXmpLuZgoO1QdIWoBYcdvFHTo65tIgi17+DTuuBx2KzeIpJndbmIpYiR9G++mwK3z9gRNJEX5VQmbI2ppyN7EvAWS9Nb/D8E3sS05LV7Yz5oI2PC3k8hnKOCVWtb2Oj7t/Cx42ts5SwCPFFIvgiyRXislVX/T+l6MgCG7Ym04HVkFCSZ6ZguhgT7ifRECAuCKYqM4K0kArZf/dNN7IK6KVvtyqMK16wDGdX667t7/7lPg2ULdscrjbuwWxnvobLXuqoGxL3sVF04roY2XVD7D/fEh2Np25dV+jxYxe8pibS7AuSzJMIpXG8LPq24l9731imZclw8YH8mvjRgFLTDXRr61/xPd8SusJ3FZzh6fVpLCnlERvHraLbrPXho9cBo67DjRE76mPpV5eoAD45xoj1V0/KP7FzcpCA="
  on:
    tags: true
    repo: jivago-python/jivago-streams
